services:
  - type: web
    name: yangdomany
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    
  - type: cron
    name: kopis-sync
    env: python
    schedule: "0 2 * * *"  # 매일 새벽 2시
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python kopis_sync.py"